// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: motor_init.proto

#include "motor_init.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace messages {
namespace motor {
PROTOBUF_CONSTEXPR Motor_Init_Req::Motor_Init_Req(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.can_bus_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.motor_type_)*/0
  , /*decltype(_impl_.can_id_)*/0
  , /*decltype(_impl_.p_)*/0
  , /*decltype(_impl_.i_)*/0
  , /*decltype(_impl_.d_)*/0} {}
struct Motor_Init_ReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Motor_Init_ReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Motor_Init_ReqDefaultTypeInternal() {}
  union {
    Motor_Init_Req _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Motor_Init_ReqDefaultTypeInternal _Motor_Init_Req_default_instance_;
PROTOBUF_CONSTEXPR Motor_Init_Rep::Motor_Init_Rep(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.motor_topic_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_.motorindex_)*/0} {}
struct Motor_Init_RepDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Motor_Init_RepDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Motor_Init_RepDefaultTypeInternal() {}
  union {
    Motor_Init_Rep _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Motor_Init_RepDefaultTypeInternal _Motor_Init_Rep_default_instance_;
}  // namespace motor
}  // namespace messages
static ::_pb::Metadata file_level_metadata_motor_5finit_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_motor_5finit_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_motor_5finit_2eproto = nullptr;

const uint32_t TableStruct_motor_5finit_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _impl_.motor_type_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _impl_.can_id_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _impl_.can_bus_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _impl_.p_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _impl_.i_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Req, _impl_.d_),
  1,
  2,
  0,
  3,
  4,
  5,
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Rep, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Rep, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Rep, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Rep, _impl_.motorindex_),
  PROTOBUF_FIELD_OFFSET(::messages::motor::Motor_Init_Rep, _impl_.motor_topic_),
  1,
  2,
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 12, -1, sizeof(::messages::motor::Motor_Init_Req)},
  { 18, 27, -1, sizeof(::messages::motor::Motor_Init_Rep)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::messages::motor::_Motor_Init_Req_default_instance_._instance,
  &::messages::motor::_Motor_Init_Rep_default_instance_._instance,
};

const char descriptor_table_protodef_motor_5finit_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020motor_init.proto\022\016messages.motor\"\327\001\n\016M"
  "otor_Init_Req\0222\n\nmotor_type\030\001 \001(\0162\031.mess"
  "ages.motor.MotorTypeH\000\210\001\001\022\023\n\006can_id\030\002 \001("
  "\005H\001\210\001\001\022\024\n\007can_bus\030\003 \001(\tH\002\210\001\001\022\016\n\001p\030\004 \001(\001H"
  "\003\210\001\001\022\016\n\001i\030\005 \001(\001H\004\210\001\001\022\016\n\001d\030\006 \001(\001H\005\210\001\001B\r\n\013"
  "_motor_typeB\t\n\007_can_idB\n\n\010_can_busB\004\n\002_p"
  "B\004\n\002_iB\004\n\002_d\"\204\001\n\016Motor_Init_Rep\022\024\n\007succe"
  "ss\030\001 \001(\010H\000\210\001\001\022\027\n\nmotorIndex\030\002 \001(\005H\001\210\001\001\022\030"
  "\n\013motor_topic\030\003 \001(\tH\002\210\001\001B\n\n\010_successB\r\n\013"
  "_motorIndexB\016\n\014_motor_topic*V\n\tMotorType"
  "\022\016\n\nMotor_NONE\020\000\022\022\n\016Motor_TalonSRX\020\001\022\021\n\r"
  "Motor_TalonFX\020\002\022\022\n\016Motor_SparkMax\020\003b\006pro"
  "to3"
  ;
static ::_pbi::once_flag descriptor_table_motor_5finit_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_motor_5finit_2eproto = {
    false, false, 483, descriptor_table_protodef_motor_5finit_2eproto,
    "motor_init.proto",
    &descriptor_table_motor_5finit_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_motor_5finit_2eproto::offsets,
    file_level_metadata_motor_5finit_2eproto, file_level_enum_descriptors_motor_5finit_2eproto,
    file_level_service_descriptors_motor_5finit_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_motor_5finit_2eproto_getter() {
  return &descriptor_table_motor_5finit_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_motor_5finit_2eproto(&descriptor_table_motor_5finit_2eproto);
namespace messages {
namespace motor {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MotorType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_motor_5finit_2eproto);
  return file_level_enum_descriptors_motor_5finit_2eproto[0];
}
bool MotorType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class Motor_Init_Req::_Internal {
 public:
  using HasBits = decltype(std::declval<Motor_Init_Req>()._impl_._has_bits_);
  static void set_has_motor_type(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_can_id(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_can_bus(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_p(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_i(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_d(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
};

Motor_Init_Req::Motor_Init_Req(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messages.motor.Motor_Init_Req)
}
Motor_Init_Req::Motor_Init_Req(const Motor_Init_Req& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Motor_Init_Req* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.can_bus_){}
    , decltype(_impl_.motor_type_){}
    , decltype(_impl_.can_id_){}
    , decltype(_impl_.p_){}
    , decltype(_impl_.i_){}
    , decltype(_impl_.d_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.can_bus_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.can_bus_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_can_bus()) {
    _this->_impl_.can_bus_.Set(from._internal_can_bus(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.motor_type_, &from._impl_.motor_type_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.d_) -
    reinterpret_cast<char*>(&_impl_.motor_type_)) + sizeof(_impl_.d_));
  // @@protoc_insertion_point(copy_constructor:messages.motor.Motor_Init_Req)
}

inline void Motor_Init_Req::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.can_bus_){}
    , decltype(_impl_.motor_type_){0}
    , decltype(_impl_.can_id_){0}
    , decltype(_impl_.p_){0}
    , decltype(_impl_.i_){0}
    , decltype(_impl_.d_){0}
  };
  _impl_.can_bus_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.can_bus_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Motor_Init_Req::~Motor_Init_Req() {
  // @@protoc_insertion_point(destructor:messages.motor.Motor_Init_Req)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Motor_Init_Req::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.can_bus_.Destroy();
}

void Motor_Init_Req::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Motor_Init_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:messages.motor.Motor_Init_Req)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.can_bus_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x0000003eu) {
    ::memset(&_impl_.motor_type_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.d_) -
        reinterpret_cast<char*>(&_impl_.motor_type_)) + sizeof(_impl_.d_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Motor_Init_Req::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .messages.motor.MotorType motor_type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_motor_type(static_cast<::messages::motor::MotorType>(val));
        } else
          goto handle_unusual;
        continue;
      // optional int32 can_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_can_id(&has_bits);
          _impl_.can_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string can_bus = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_can_bus();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "messages.motor.Motor_Init_Req.can_bus"));
        } else
          goto handle_unusual;
        continue;
      // optional double p = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_p(&has_bits);
          _impl_.p_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double i = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 41)) {
          _Internal::set_has_i(&has_bits);
          _impl_.i_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // optional double d = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 49)) {
          _Internal::set_has_d(&has_bits);
          _impl_.d_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Motor_Init_Req::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messages.motor.Motor_Init_Req)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional .messages.motor.MotorType motor_type = 1;
  if (_internal_has_motor_type()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_motor_type(), target);
  }

  // optional int32 can_id = 2;
  if (_internal_has_can_id()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_can_id(), target);
  }

  // optional string can_bus = 3;
  if (_internal_has_can_bus()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_can_bus().data(), static_cast<int>(this->_internal_can_bus().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messages.motor.Motor_Init_Req.can_bus");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_can_bus(), target);
  }

  // optional double p = 4;
  if (_internal_has_p()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_p(), target);
  }

  // optional double i = 5;
  if (_internal_has_i()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(5, this->_internal_i(), target);
  }

  // optional double d = 6;
  if (_internal_has_d()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(6, this->_internal_d(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messages.motor.Motor_Init_Req)
  return target;
}

size_t Motor_Init_Req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messages.motor.Motor_Init_Req)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional string can_bus = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_can_bus());
    }

    // optional .messages.motor.MotorType motor_type = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::_pbi::WireFormatLite::EnumSize(this->_internal_motor_type());
    }

    // optional int32 can_id = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_can_id());
    }

    // optional double p = 4;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 8;
    }

    // optional double i = 5;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 + 8;
    }

    // optional double d = 6;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 + 8;
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Motor_Init_Req::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Motor_Init_Req::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Motor_Init_Req::GetClassData() const { return &_class_data_; }


void Motor_Init_Req::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Motor_Init_Req*>(&to_msg);
  auto& from = static_cast<const Motor_Init_Req&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messages.motor.Motor_Init_Req)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_can_bus(from._internal_can_bus());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.motor_type_ = from._impl_.motor_type_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.can_id_ = from._impl_.can_id_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.p_ = from._impl_.p_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.i_ = from._impl_.i_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.d_ = from._impl_.d_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Motor_Init_Req::CopyFrom(const Motor_Init_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messages.motor.Motor_Init_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Motor_Init_Req::IsInitialized() const {
  return true;
}

void Motor_Init_Req::InternalSwap(Motor_Init_Req* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.can_bus_, lhs_arena,
      &other->_impl_.can_bus_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Motor_Init_Req, _impl_.d_)
      + sizeof(Motor_Init_Req::_impl_.d_)
      - PROTOBUF_FIELD_OFFSET(Motor_Init_Req, _impl_.motor_type_)>(
          reinterpret_cast<char*>(&_impl_.motor_type_),
          reinterpret_cast<char*>(&other->_impl_.motor_type_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Motor_Init_Req::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_motor_5finit_2eproto_getter, &descriptor_table_motor_5finit_2eproto_once,
      file_level_metadata_motor_5finit_2eproto[0]);
}

// ===================================================================

class Motor_Init_Rep::_Internal {
 public:
  using HasBits = decltype(std::declval<Motor_Init_Rep>()._impl_._has_bits_);
  static void set_has_success(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_motorindex(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_motor_topic(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Motor_Init_Rep::Motor_Init_Rep(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:messages.motor.Motor_Init_Rep)
}
Motor_Init_Rep::Motor_Init_Rep(const Motor_Init_Rep& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Motor_Init_Rep* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.motor_topic_){}
    , decltype(_impl_.success_){}
    , decltype(_impl_.motorindex_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.motor_topic_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.motor_topic_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_motor_topic()) {
    _this->_impl_.motor_topic_.Set(from._internal_motor_topic(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.success_, &from._impl_.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.motorindex_) -
    reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.motorindex_));
  // @@protoc_insertion_point(copy_constructor:messages.motor.Motor_Init_Rep)
}

inline void Motor_Init_Rep::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.motor_topic_){}
    , decltype(_impl_.success_){false}
    , decltype(_impl_.motorindex_){0}
  };
  _impl_.motor_topic_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.motor_topic_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Motor_Init_Rep::~Motor_Init_Rep() {
  // @@protoc_insertion_point(destructor:messages.motor.Motor_Init_Rep)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Motor_Init_Rep::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.motor_topic_.Destroy();
}

void Motor_Init_Rep::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Motor_Init_Rep::Clear() {
// @@protoc_insertion_point(message_clear_start:messages.motor.Motor_Init_Rep)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.motor_topic_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.success_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.motorindex_) -
        reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.motorindex_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Motor_Init_Rep::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_success(&has_bits);
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 motorIndex = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_motorindex(&has_bits);
          _impl_.motorindex_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string motor_topic = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_motor_topic();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "messages.motor.Motor_Init_Rep.motor_topic"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Motor_Init_Rep::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:messages.motor.Motor_Init_Rep)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional bool success = 1;
  if (_internal_has_success()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // optional int32 motorIndex = 2;
  if (_internal_has_motorindex()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_motorindex(), target);
  }

  // optional string motor_topic = 3;
  if (_internal_has_motor_topic()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_motor_topic().data(), static_cast<int>(this->_internal_motor_topic().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "messages.motor.Motor_Init_Rep.motor_topic");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_motor_topic(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messages.motor.Motor_Init_Rep)
  return target;
}

size_t Motor_Init_Rep::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:messages.motor.Motor_Init_Rep)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional string motor_topic = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_motor_topic());
    }

    // optional bool success = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + 1;
    }

    // optional int32 motorIndex = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_motorindex());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Motor_Init_Rep::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Motor_Init_Rep::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Motor_Init_Rep::GetClassData() const { return &_class_data_; }


void Motor_Init_Rep::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Motor_Init_Rep*>(&to_msg);
  auto& from = static_cast<const Motor_Init_Rep&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:messages.motor.Motor_Init_Rep)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_motor_topic(from._internal_motor_topic());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.success_ = from._impl_.success_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.motorindex_ = from._impl_.motorindex_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Motor_Init_Rep::CopyFrom(const Motor_Init_Rep& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:messages.motor.Motor_Init_Rep)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Motor_Init_Rep::IsInitialized() const {
  return true;
}

void Motor_Init_Rep::InternalSwap(Motor_Init_Rep* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.motor_topic_, lhs_arena,
      &other->_impl_.motor_topic_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Motor_Init_Rep, _impl_.motorindex_)
      + sizeof(Motor_Init_Rep::_impl_.motorindex_)
      - PROTOBUF_FIELD_OFFSET(Motor_Init_Rep, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Motor_Init_Rep::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_motor_5finit_2eproto_getter, &descriptor_table_motor_5finit_2eproto_once,
      file_level_metadata_motor_5finit_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace motor
}  // namespace messages
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::messages::motor::Motor_Init_Req*
Arena::CreateMaybeMessage< ::messages::motor::Motor_Init_Req >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messages::motor::Motor_Init_Req >(arena);
}
template<> PROTOBUF_NOINLINE ::messages::motor::Motor_Init_Rep*
Arena::CreateMaybeMessage< ::messages::motor::Motor_Init_Rep >(Arena* arena) {
  return Arena::CreateMessageInternal< ::messages::motor::Motor_Init_Rep >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
